### ISSUE TITLE
generateDoWhileLoopStatement is wrong

### ISSUE THREAD

**Issue by ProHolz** [remobjects/CodeGen4#10]
#9 generateDoWhileLoopStatement will solve as: repeat until not [condition] if no operator in statement

**Comment by dwarfland** [comment]
I don't understand. This seems as designed? `repeat until` required a revered clause compared to `do while`.

**Comment by ProHolz** [comment]
I have created a pull request to solve it. #9 

```pascal
repeat
// Some code
until resolved; 
```

The result in the actual codegGen4 will always be 

```pascal
repeat
// Some code
until **not** resolved; 

```

**Comment by dwarfland** [comment]
Yes, this is the *correct* behavior.

**Comment by ProHolz** [comment]
now I don't understand :-)
_correct_ in which aspect?
